version: '3'
services:
        web:
                image: maniacflask_v2
                build: .
                ports:
                        - "8024:8086"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
